### PR TITLE
Fixes #9

### LINKED ISSUE #9: Api error message does not throw an exception
Instead of throwing a `GeolocationException` an empty point is returned, this happens for example when your api limit has been reached:
```
{ 
"error_message" : "You have exceeded your daily request quota for this API. We recommend registering for a key at the Google Developers Console: https://console.developers.google.com/apis/credentials?project=_",
"results" : [],
"status" : "OVER_QUERY_LIMIT" 
}
```

### PR DESCRIPTION
**Pull request by janverton**
Throws an exception with the `error_message` returned by the API as message instead of returning an empty lat/long

### CODE REVIEW

File: src/Geolocation.php [hunk 1]
```diff
@@ -79,6 +79,9 @@ protected function doCall($parameters = array())
         // redefine response as json decoded
         $response = json_decode($response);
 
+        // API returns with an error
+        if (isset($response->error_message)) throw new GeolocationException($response->error_message);
```
Comment (jeroendesloovere) [inline src/Geolocation.php]: Can you change it to:

```
if (isset($response->error_message)) {
    throw new GeolocationException($response->error_message);
}
```

Comment (janverton) [reply src/Geolocation.php]: Sure will do, although it breaks convention regarding the rest of the class :)

**Comment by jeroendesloovere** [comment]
Hi @janverton, I just released 1.4.1.

**Comment by janverton** [comment]
Thanks!
